package com.hand.model;
// Generated 2015-8-31 17:58:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Rental generated by hbm2java
 */
@Entity
@Table(name = "rental", catalog = "sakila", uniqueConstraints = @UniqueConstraint(columnNames = { "rental_date",
		"inventory_id", "customer_id" }) )
public class Rental implements java.io.Serializable {

	private Integer rentalId;
	private Customer customer;
	private Date rentalDate;
	private int inventoryId;
	private Date returnDate;
	private byte staffId;
	private Date lastUpdate;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Rental() {
	}

	public Rental(Customer customer, Date rentalDate, int inventoryId, byte staffId, Date lastUpdate) {
		this.customer = customer;
		this.rentalDate = rentalDate;
		this.inventoryId = inventoryId;
		this.staffId = staffId;
		this.lastUpdate = lastUpdate;
	}

	public Rental(Customer customer, Date rentalDate, int inventoryId, Date returnDate, byte staffId, Date lastUpdate,
			Set<Payment> payments) {
		this.customer = customer;
		this.rentalDate = rentalDate;
		this.inventoryId = inventoryId;
		this.returnDate = returnDate;
		this.staffId = staffId;
		this.lastUpdate = lastUpdate;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rental_id", unique = true, nullable = false)
	public Integer getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Integer rentalId) {
		this.rentalId = rentalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rental_date", nullable = false, length = 19)
	public Date getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}

	@Column(name = "inventory_id", nullable = false)
	public int getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(int inventoryId) {
		this.inventoryId = inventoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "return_date", length = 19)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Column(name = "staff_id", nullable = false)
	public byte getStaffId() {
		return this.staffId;
	}

	public void setStaffId(byte staffId) {
		this.staffId = staffId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rental")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
